In [ ]:
'''
Animesh Chaudhry 
HW 3
Math 440 
10/20/2019
Ch 9  Section 4 Problem 2
'''

In [1]:
'''
Use Householder’s method to produce a symmetric tridiagonal matrix that is similar to the given
matrix.
'''
import numpy as np
from string import ascii_lowercase

def householder(A):
    
    for i in range(len(A)-2):
        alpha = -(A[1][0]/abs(A[1][0]))*(np.sum(A[1:4,0]**2)**.5)
        r = (.5*alpha**2-.5*A[1][0]*alpha)**.5
        w = np.zeros(len(A))
        w[1] = (A[1][0]-alpha)/(2*r)
        for j in range(len(A)-2):
            w[j+2] = (A[j+2][0])/(2*r)
        wt = w.reshape(len(A),1)
        P = np.eye(len(A))-2*wt*w
        A = np.matmul(P,np.matmul(A,P))
    
    return np.round(A,5)



a = np.array([[4,-1,-1,0], [-1,4,0,-1], [-1,0,4,-1],[0,-1,-1,4]])
b = np.array([[5,-2,-0.5,1.5], [-2,5,1.5,-0.5], [-0.5,1.5,5,-2],[1.5,-0.5,-2,5]])
c = np.array([[8,0.25,0.5,2,-1], [0.24,-4,0,1,2], [0.5,0,5,0.75,-1],[2,1,-.75,5,-0.5], [-1,2,-1,-0.5,6]])
d = np.array([[2,-1,-1,0,0], [-1,3,0,-2,0], [-1,0,4,2,1],[0,-2,2,8,3], [0,0,1,3,9]])

def print_hld(A, part):
    print(f"-------------------------------------------------\n{part}: \n{A}\n \nSymmetric tridiagonal matrix that is similar to {part}: \n{householder(A)}\n-------------------------------------------------\n\n\n")

matrices = [a,b,c,d]
for c, i in zip(matrices, ascii_lowercase):
    print_hld(c, i)



-------------------------------------------------
a: 
[[ 4 -1 -1  0]
 [-1  4  0 -1]
 [-1  0  4 -1]
 [ 0 -1 -1  4]]
 
Symmetric tridiagonal matrix that is similar to a: 
[[ 4.      -1.41421  0.       0.     ]
 [-1.41421  4.       0.      -1.41421]
 [ 0.       0.       4.       0.     ]
 [ 0.      -1.41421  0.       4.     ]]
-------------------------------------------------



-------------------------------------------------
b: 
[[ 5.  -2.  -0.5  1.5]
 [-2.   5.   1.5 -0.5]
 [-0.5  1.5  5.  -2. ]
 [ 1.5 -0.5 -2.   5. ]]
 
Symmetric tridiagonal matrix that is similar to b: 
[[ 5.      -2.54951  0.       0.     ]
 [-2.54951  6.38462  2.13656 -0.13397]
 [ 0.       2.13656  4.18395 -0.68116]
 [ 0.      -0.13397 -0.68116  4.43144]]
-------------------------------------------------



-------------------------------------------------
c: 
[[ 8.    0.25  0.5   2.   -1.  ]
 [ 0.24 -4.    0.    1.    2.  ]
 [ 0.5   0.    5.    0.75 -1.  ]
 [ 2.    1.   -0.75  5.   -0.5 ]
 [-1.    2.   -1.   -0.5