In [ ]:
'''
Animesh Chaudhry 
HW 3
Math 440 
10/20/2019
Ch 9  Section 3 Problem 1
'''

In [64]:
'''
Find the first 3 iterations obtained by the Power method applied to the following matrices.
'''

import numpy as np
from decimal import *

def power(A, x_0=None, TOL=1e-6, max_itr=50):

    
    n, m = A.shape
    
    if x_0 is None:
        x_0 = np.ones((n,1))
    else:
        if (n != len(x_0)):
            print("The starting vector x_0 does not have the correct dimensions")
            return None
        else:
            x_0 = np.array(x_0).reshape(n,1)
            
            
    
    if n != m:
        print("Matrix not Square")
        return None
    
    
    abs_d = 1/TOL
    
    zcol = np.zeros((n,1))
    x = x_0
    y = zcol
    mu = [0]
    
    i = 1
    while abs_d > TOL:
        
        # Initialize
        x = np.hstack((x,zcol))
        y = np.hstack((y,zcol))
        mu.append(0)
        # y = Ax
        y[:, i] = np.dot(A, x[:,i-1])
        # mu = y_p0, where p_0 is the max value 
        mu[i] = max(abs(y[:,i]))
        # x = y/mu
        x[:, i] = y[:,i]/mu[i]
        
        abs_d = max(abs( x[:,-1] -  x[:, -2])) / max(abs(x[:,-1]))
        
        if i > 3:
            break
        print(f"\nIteration # {i}\n x = {x[:,-1]} \n Mu = {mu[-1]}\n")
        
        i += 1
        if i > max_itr:
            return None
        
    print("The dominant eigenvalue is {}, and the eigenvector associated is \n{}\n\n\n===============================================================================\n\n\n".format(mu[-1], x[:,-1]))


    
def print_ans(A, x_0=None):
    print(f"===============================================================================\nA = \n{A} \nx_0 = {x_0}")
    
A = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
a = [1,-1,2]
B = np.array([[1, 1, 1], [1, 1, 0], [1, 0, 1]])
b = [-1,0,1]
C = np.array([[1,-1,0],[-2,4,-2],[0,-1,2]])
c = [-1,2,1]
D = np.array([[4,1,1,1],[1,3,-1,1],[1,-1,2,0], [1,1,0,2]])
d = [1,-2,0,3]
E = np.array([[5,-2,-1/2,3/2],[-2,5,3/2,-1/2],[-1/2,3/2,5,-2], [3/2,-1/2,-2,5]])
e = [1,1,0,-3]
F = np.array([[-4,0,1/2,1/2],[1/2,-2,0,1/2],[1/2,1/2,0,0], [0,1,1,4]])
f = [0,0,0,1]


matrices = [A,B,C,D,E,F]
x_vec = [a,b,c,d,e,f]
for i, c in zip(matrices, x_vec):
    print_ans(i,c)
    power(i,c)




A = 
[[2 1 1]
 [1 2 1]
 [1 1 2]] 
x_0 = [1, -1, 2]

Iteration # 1
 x = [0.75 0.25 1.  ] 
 Mu = 4.0


Iteration # 2
 x = [0.91666667 0.75       1.        ] 
 Mu = 3.0


Iteration # 3
 x = [0.97727273 0.93181818 1.        ] 
 Mu = 3.6666666666666665

The dominant eigenvalue is 3.909090909090909, and the eigenvector associated is 
[0.99418605 0.98255814 1.        ]





A = 
[[1 1 1]
 [1 1 0]
 [1 0 1]] 
x_0 = [-1, 0, 1]

Iteration # 1
 x = [ 0. -1.  0.] 
 Mu = 1.0


Iteration # 2
 x = [-1. -1.  0.] 
 Mu = 1.0


Iteration # 3
 x = [-1.  -1.  -0.5] 
 Mu = 2.0

The dominant eigenvalue is 2.5, and the eigenvector associated is 
[-1.  -0.8 -0.6]





A = 
[[ 1 -1  0]
 [-2  4 -2]
 [ 0 -1  2]] 
x_0 = [-1, 2, 1]

Iteration # 1
 x = [-0.375  1.     0.   ] 
 Mu = 8.0


Iteration # 2
 x = [-0.28947368  1.         -0.21052632] 
 Mu = 4.75


Iteration # 3
 x = [-0.25789474  1.         -0.28421053] 
 Mu = 5.0

The dominant eigenvalue is 5.08421052631579, and the eigenvector associated is 
[-0.24741201 