In [16]:
'''
Animesh Chaudhry 
HW 3
Math 440 
10/20/2019
Ch 9  Section 4 Problem 1
'''

'\nAnimesh Chaudhry \nHW 3\nMath 440 \n10/20/2019\nCh 9  Section 4 Problem 1 and 2\n'

In [17]:
'''
Use Householder’s method to produce a symmetric tridiagonal matrix that is similar to the given
matrix.
'''
import numpy as np
from string import ascii_lowercase

def householder(A):
    
    for i in range(len(A)-2):
        alpha = -(A[1][0]/abs(A[1][0]))*(np.sum(A[1:4,0]**2)**.5)
        r = (.5*alpha**2-.5*A[1][0]*alpha)**.5
        w = np.zeros(len(A))
        w[1] = (A[1][0]-alpha)/(2*r)
        for j in range(len(A)-2):
            w[j+2] = (A[j+2][0])/(2*r)
        wt = w.reshape(len(A),1)
        P = np.eye(len(A))-2*wt*w
        A = np.matmul(P,np.matmul(A,P))
    
    return np.round(A,5)


a = np.array([[12, 10, 4], [10,8,-5],[4,-5,3]])
b = np.array([[2, -1, -1], [-1,2,-1],[-1,-1,2]])
c = np.array([[1, 1, 1], [1,1, 0],[1,0,1]])
d = np.array([[4.75, 2.25, -0.25], [2.25,4.75,1.25],[-0.25,1.25,4.75]])


def print_hld(A, part):
    print(f"-------------------------------------------------\n{part}: \n{A}\n \nSymmetric tridiagonal matrix that is similar to {part}: \n{householder(A)}\n-------------------------------------------------\n\n\n")

matrices = [a,b,c,d]
for c, i in zip(matrices, ascii_lowercase):
    print_hld(c, i)



-------------------------------------------------
a: 
[[12 10  4]
 [10  8 -5]
 [ 4 -5  3]]
 
Symmetric tridiagonal matrix that is similar to a: 
[[ 12.      -10.77033   0.     ]
 [-10.77033   3.86207   5.34483]
 [  0.        5.34483   7.13793]]
-------------------------------------------------



-------------------------------------------------
b: 
[[ 2 -1 -1]
 [-1  2 -1]
 [-1 -1  2]]
 
Symmetric tridiagonal matrix that is similar to b: 
[[ 2.       1.41421  0.     ]
 [ 1.41421  1.      -0.     ]
 [ 0.      -0.       3.     ]]
-------------------------------------------------



-------------------------------------------------
c: 
[[1 1 1]
 [1 1 0]
 [1 0 1]]
 
Symmetric tridiagonal matrix that is similar to c: 
[[ 1.      -1.41421  0.     ]
 [-1.41421  1.      -0.     ]
 [ 0.      -0.       1.     ]]
-------------------------------------------------



-------------------------------------------------
d: 
[[ 4.75  2.25 -0.25]
 [ 2.25  4.75  1.25]
 [-0.25  1.25  4.75]]
 
Symmetric tri