In [ ]:
'''
Animesh Chaudhry 
HW 3
Math 440 
10/20/2019
Ch 9  Section 2 problem 2
'''

In [34]:
'''
(2)

Find the eigenvalues and associated eigenvectors for the following 3 × 3 matrices. Is there a set of
three linearly independent eigenvectors?
'''
import numpy as np
from numpy import linalg as LA
from string import ascii_lowercase

a = np.array([[2, -3, 6], [0, 3, -4], [0, 2, -3]])
b = np.array([[1, 0, 0], [-1, 0, 1], [-1, -1, 2]])
c = np.array([[2, 0, -1], [0, 2, 0], [1, 0, 2]])
d = np.array([[2, -1, -1], [-1, 2, -1], [-1, -1, 2]])
e = np.array([[1, 1, 1], [1, 1, 0], [1, 0, 1]])
f = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])

def print_egn(A):
    print(f"{A} \nEigenValue(s): ----> {LA.eig(A)[0]}\nEigenvectors: ----> \n{LA.eig(A)[1]}\nDeterminent of eigenvector matrix: {np.linalg.det(np.array(LA.eig(A)[1]))}\n\n")

matrices = [a,b,c,d, e,f]
for i in matrices:
    print_egn(i)
print(f"If the determinent of eigenvector matrix is a number fairly close to zero, then the vectors are not L.I., otherwise, they are")

[[ 2 -3  6]
 [ 0  3 -4]
 [ 0  2 -3]] 
EigenValue(s): ----> [ 2.  1. -1.]
Eigenvectors: ----> 
[[ 1.00000000e+00  1.11022302e-16 -5.77350269e-01]
 [ 0.00000000e+00  8.94427191e-01  5.77350269e-01]
 [ 0.00000000e+00  4.47213595e-01  5.77350269e-01]]
Determinent of eigenvector matrix: 0.2581988897471612


[[ 1  0  0]
 [-1  0  1]
 [-1 -1  2]] 
EigenValue(s): ----> [1. 1. 1.]
Eigenvectors: ----> 
[[0.00000000e+00 0.00000000e+00 5.36063097e-16]
 [7.07106781e-01 7.07106781e-01 7.07106781e-01]
 [7.07106781e-01 7.07106781e-01 7.07106781e-01]]
Determinent of eigenvector matrix: -6.673533456052385e-32


[[ 2  0 -1]
 [ 0  2  0]
 [ 1  0  2]] 
EigenValue(s): ----> [2.+1.j 2.-1.j 2.+0.j]
Eigenvectors: ----> 
[[0.70710678+0.j         0.70710678-0.j         0.        +0.j        ]
 [0.        +0.j         0.        -0.j         1.        +0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j 0.        +0.j        ]]
Determinent of eigenvector matrix: -0.9999999999999999j


[[ 2 -1 -1]
 [-1  2 -1